<?
class CFG{
  const IBLOCK_NEWS = 1;
  const IBLOCK_COMMENT_NEWS = 2;
  const IBLOCK_CONTACTS = 3;
  const IBLOCK_TRADING_CONDITIONS = 4;
  const IBLOCK_DOCS = 5;
  const IBLOCK_DEPOSITING = 7;
  const IBLOCK_USERS_DOCS = 8;
  const IBLOCK_SLIDER = 9;
  const IBLOCK_REVIEWS = 10;
  const IBLOCK_CERTIFICATES = 11;
  const IBLOCK_GLOSSARY = 12;
  const IBLOCK_PROMOTIONS = 13;
  const IBLOCK_LESSONS = 14;
  const IBLOCK_LECTURES = 15;
  const IBLOCK_FAQ = 16;

  const SECTION_HISTORY = 4;
  const SECTION_WHY = 11;

  const ELEMENT_ABOUT = 25;

}